apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: gcr.io/hello-minikube-zero-install/hello-node
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  type: LoadBalancer
  ports:
    -
      name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: web-app
