apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    spec:
      containers:
      - name: hello-world
        image: marcandreg/mock:hello
        ports:
        - containerPort: 3000